# Generated by Django 5.2.5 on 2025-09-04 15:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('INICIAL', 'Inicial'), ('SEGUIMIENTO', 'Seguimiento')], default='INICIAL', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('respuestas', models.JSONField(blank=True, default=list)),
                ('metricas', models.JSONField(blank=True, default=dict)),
                ('plantilla_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='user.nutricionista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='user.paciente')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['fecha'], name='user_consul_fecha_a5782f_idx'), models.Index(fields=['tipo'], name='user_consul_tipo_9f7a05_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('integer', 'Entero'), ('decimal', 'Decimal'), ('boolean', 'Sí/No'), ('date', 'Fecha'), ('single', 'Opción única'), ('multi', 'Opción múltiple')], max_length=10)),
                ('codigo', models.CharField(blank=True, default='', max_length=50)),
                ('requerido', models.BooleanField(default=False)),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('unidad', models.CharField(blank=True, default='', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('es_inicial', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='user.nutricionista')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['owner'], name='user_pregun_owner_i_7b8116_idx'), models.Index(fields=['codigo'], name='user_pregun_codigo_93b525_idx'), models.Index(fields=['activo', 'es_inicial'], name='user_pregun_activo_c5fb98_idx'), models.Index(fields=['orden'], name='user_pregun_orden_8d9e1a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('codigo', ''), _negated=True), fields=('owner', 'codigo'), name='uq_pregunta_owner_codigo')],
            },
        ),
    ]
