# Generated by Django 5.2.5 on 2025-10-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_consulta_pregunta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'cuenta de usuario', 'verbose_name_plural': 'cuentas de usuario'},
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, verbose_name='apellido'),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserSecurity',
        ),
    ]
