# Generated by Django 5.2.5 on 2025-10-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_useraccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='profile_pictures/'),
        ),
    ]
