# Generated by Django 5.2.5 on 2025-10-25 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useraccount_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición en la plantilla')),
                ('requerido_en_plantilla', models.BooleanField(default=False, help_text='Override: puede ser opcional en Pregunta pero requerida en esta plantilla')),
                ('visible', models.BooleanField(default=True, help_text='Si está oculta, no se muestra pero puede usarse para cálculos')),
                ('config', models.JSONField(blank=True, default=dict, help_text="Ej: {valor_default: '0', placeholder: 'Ingresar peso en kg', ayuda_extra: '...'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pregunta en plantilla',
                'verbose_name_plural': 'preguntas en plantillas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Consulta Diabetes', 'Primera vez deportistas'", max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_consulta', models.CharField(choices=[('INICIAL', 'Inicial'), ('SEGUIMIENTO', 'Seguimiento')], default='INICIAL', help_text='Tipo de consulta para la que se usa esta plantilla', max_length=15)),
                ('es_predeterminada', models.BooleanField(default=False, help_text='Si es True, se usa automáticamente para nuevas consultas de este tipo')),
                ('activo', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text="Ej: {calcular_imc: true, mostrar_graficos: false, color: '#4F46E5'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='NULL = plantilla del sistema, con valor = plantilla del nutricionista', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_consulta', to='user.nutricionista')),
            ],
            options={
                'verbose_name': 'plantilla de consulta',
                'verbose_name_plural': 'plantillas de consulta',
                'ordering': ['-es_predeterminada', 'tipo_consulta', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='plantilla_usada',
            field=models.ForeignKey(blank=True, help_text='Plantilla que se usó para crear esta consulta. NULL si fue manual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_realizadas', to='user.plantillaconsulta'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['plantilla_usada'], name='user_consul_plantil_348acc_idx'),
        ),
        migrations.AddField(
            model_name='plantillapregunta',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_config', to='user.plantillaconsulta'),
        ),
        migrations.AddField(
            model_name='plantillapregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_en_plantillas', to='user.pregunta'),
        ),
        migrations.AddIndex(
            model_name='plantillaconsulta',
            index=models.Index(fields=['owner', 'activo'], name='user_planti_owner_i_1fd8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillaconsulta',
            index=models.Index(fields=['tipo_consulta', 'es_predeterminada'], name='user_planti_tipo_co_f4484d_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillaconsulta',
            index=models.Index(fields=['created_at'], name='user_planti_created_6a5cba_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillapregunta',
            index=models.Index(fields=['plantilla', 'orden'], name='user_planti_plantil_e0e419_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillapregunta',
            index=models.Index(fields=['pregunta'], name='user_planti_pregunt_de0cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='plantillapregunta',
            index=models.Index(fields=['visible'], name='user_planti_visible_39fffd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plantillapregunta',
            unique_together={('plantilla', 'pregunta')},
        ),
    ]
