# Generated by Django 5.2.5 on 2025-10-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_plantillapregunta_plantillaconsulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='email_host',
            field=models.CharField(blank=True, help_text='Servidor SMTP (ej: smtp.gmail.com)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='email_password',
            field=models.CharField(blank=True, help_text='Contraseña de aplicación o contraseña del email', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='email_port',
            field=models.IntegerField(blank=True, default=587, help_text='Puerto SMTP (587 para TLS, 465 para SSL)', null=True),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='Usar SSL para conexión segura (incompatible con TLS)'),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Usar TLS para conexión segura'),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='email_username',
            field=models.EmailField(blank=True, help_text='Email desde el cual enviar (ej: nutricionista@gmail.com)', max_length=254, null=True),
        ),
    ]
