# Generated by Django 5.2.5 on 2025-11-13 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_cleanup_plantillacategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAlimentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del plan alimentario', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del plan')),
                ('archivo', models.FileField(help_text='Archivo del plan alimentario (PDF, DOCX, XLSX, imágenes, etc.)', upload_to='planes_alimentarios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nutricionista', models.ForeignKey(help_text='Nutricionista propietario del plan', on_delete=django.db.models.deletion.CASCADE, related_name='planes_alimentarios', to='user.nutricionista')),
            ],
            options={
                'verbose_name': 'plan alimentario',
                'verbose_name_plural': 'planes alimentarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nutricionista', '-created_at'], name='user_planal_nutrici_0a850c_idx')],
            },
        ),
    ]
