# Generated by Django 5.2.5 on 2025-10-31 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_cleanup_plantillacategoria'),
        ('user', '0006_nutricionista_email_host_and_more'),
    ]

    operations = [
    ]
