# Generated by Django 5.2.5 on 2025-11-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_planalimentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPlanAlimentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la asignación (opcional)')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nutricionista', models.ForeignKey(help_text='Nutricionista que realiza la asignación', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_planes', to='user.nutricionista')),
                ('paciente', models.ForeignKey(help_text='Paciente al que se le asigna el plan', on_delete=django.db.models.deletion.CASCADE, related_name='planes_asignados', to='user.paciente')),
                ('plan', models.ForeignKey(help_text='Plan alimentario asignado', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='user.planalimentario')),
            ],
            options={
                'verbose_name': 'asignación de plan alimentario',
                'verbose_name_plural': 'asignaciones de planes alimentarios',
                'ordering': ['-fecha_asignacion'],
                'indexes': [models.Index(fields=['paciente', '-fecha_asignacion'], name='user_asigna_pacient_d4cfb3_idx'), models.Index(fields=['nutricionista', '-fecha_asignacion'], name='user_asigna_nutrici_961e1e_idx')],
                'unique_together': {('plan', 'paciente')},
            },
        ),
    ]
