# Generated by Django 5.2.5 on 2025-09-19 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_patient_assigned_nutritionist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCalculadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.FloatField(blank=True, help_text='Peso en kilogramos', null=True)),
                ('talla_cm', models.FloatField(blank=True, help_text='Talla en centímetros', null=True)),
                ('talla_m', models.FloatField(blank=True, help_text='Talla en metros', null=True)),
                ('cintura_cm', models.FloatField(blank=True, help_text='Circunferencia de cintura en cm', null=True)),
                ('cadera_cm', models.FloatField(blank=True, help_text='Circunferencia de cadera en cm', null=True)),
                ('pliegue_tricipital_mm', models.FloatField(blank=True, help_text='Pliegue tríceps en mm', null=True)),
                ('pliegue_subescapular_mm', models.FloatField(blank=True, help_text='Pliegue subescapular en mm', null=True)),
                ('pliegue_suprailíaco_mm', models.FloatField(blank=True, help_text='Pliegue suprailíaco en mm', null=True)),
                ('actividad_fisica_nivel', models.CharField(blank=True, help_text='Nivel de actividad física', max_length=50)),
                ('get_peso_kg', models.FloatField(blank=True, help_text='Peso para cálculo GET', null=True)),
                ('get_talla_cm', models.FloatField(blank=True, help_text='Talla para cálculo GET', null=True)),
                ('get_edad', models.IntegerField(blank=True, help_text='Edad para cálculo GET', null=True)),
                ('get_sexo', models.CharField(blank=True, help_text='Sexo para cálculo GET', max_length=10)),
                ('porcentaje_grasa_input', models.FloatField(blank=True, help_text='Porcentaje de grasa (input manual)', null=True)),
                ('metodo_porcentaje_grasa', models.CharField(blank=True, help_text='Método usado para medir % grasa', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_calculadora', to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HabitosAlimenticios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comidas_por_dia', models.IntegerField(blank=True, help_text='Número de comidas al día', null=True)),
                ('tiempos_comida', models.JSONField(default=list, help_text='Tiempos de comida marcados')),
                ('salta_comidas', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('cuales_comidas_salta', models.TextField(blank=True, help_text='¿Cuáles comidas salta?')),
                ('por_que_salta', models.TextField(blank=True, help_text='¿Por qué salta comidas?')),
                ('con_quien_vive', models.TextField(blank=True, help_text='¿Con quién vive?')),
                ('quien_cocina', models.TextField(blank=True, help_text='¿Quién cocina?')),
                ('hora_levantarse', models.TimeField(blank=True, help_text='¿A qué hora se levanta?', null=True)),
                ('ingestas_fuera', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('que_ingestas_fuera', models.TextField(blank=True, help_text='¿Qué consume fuera de las comidas principales?')),
                ('frecuencia_ingestas_fuera', models.TextField(blank=True, help_text='Frecuencia de ingestas fuera de comidas')),
                ('intolerancias_alergias', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('lista_intolerancias', models.JSONField(default=list, help_text='Lista de intolerancias/alergias')),
                ('preferidos', models.TextField(blank=True, help_text='Alimentos preferidos')),
                ('desagrados', models.TextField(blank=True, help_text='Alimentos que no le gustan')),
                ('suplementos_usa', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('cuales_suplementos', models.TextField(blank=True, help_text='¿Cuáles suplementos usa?')),
                ('interfiere_emocional', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('agrega_sal', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('medios_coccion', models.JSONField(default=list, help_text='Medios de cocción principales')),
                ('agua_vasos_dia', models.IntegerField(blank=True, help_text='Vasos de agua al día', null=True)),
                ('bebidas_industriales_vasos_dia', models.IntegerField(blank=True, help_text='Vasos de bebidas industriales al día', null=True)),
                ('cafe_usa', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('cafe_veces_semana', models.IntegerField(blank=True, help_text='Veces por semana que consume café', null=True)),
                ('alcohol_usa', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('alcohol_frecuencia', models.TextField(blank=True, help_text='Frecuencia de consumo de alcohol')),
                ('mate_terere_usa', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('mate_terere_frecuencia', models.TextField(blank=True, help_text='Frecuencia de consumo de mate/tereré')),
                ('actividad_fisica_usa', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('actividad_fisica_tipo', models.TextField(blank=True, help_text='Tipo de actividad física')),
                ('actividad_fisica_frecuencia', models.TextField(blank=True, help_text='Frecuencia de actividad física')),
                ('actividad_fisica_duracion_min', models.IntegerField(blank=True, help_text='Duración en minutos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habitos_alimenticios', to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes_familiares', models.JSONField(default=list, help_text='Lista de antecedentes familiares')),
                ('enfermedades_actuales', models.JSONField(default=list, help_text='Lista de enfermedades que padece actualmente')),
                ('modifico_dieta', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('medicacion_usa', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('medicacion_detalle', models.TextField(blank=True, help_text='Detalle de la medicación actual')),
                ('cirugias_tiene', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('cirugias_detalle', models.TextField(blank=True, help_text='Detalle de cirugías recientes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadoresDietarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordatorio_24h', models.JSONField(default=list, help_text='Recordatorio de 24 horas')),
                ('frecuencia_consumo', models.JSONField(default=dict, help_text='Frecuencia de consumo de alimentos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_dietarios', to='users.patient')),
            ],
        ),
    ]
