# Generated by Django 5.2.5 on 2025-09-24 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_datoscalculadora_habitosalimenticios_historiaclinica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='Fecha de la cita')),
                ('appointment_time', models.TimeField(help_text='Hora de la cita')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No se presentó')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la cita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Duración en minutos')),
                ('consultation_type', models.CharField(choices=[('inicial', 'Consulta Inicial'), ('seguimiento', 'Consulta de Seguimiento'), ('control', 'Control')], default='seguimiento', max_length=20)),
                ('nutritionist', models.ForeignKey(limit_choices_to={'role': 'nutricionista'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
                'indexes': [models.Index(fields=['appointment_date', 'appointment_time'], name='users_appoi_appoint_7f943d_idx'), models.Index(fields=['nutritionist', 'appointment_date'], name='users_appoi_nutriti_0dc960_idx'), models.Index(fields=['patient', 'appointment_date'], name='users_appoi_patient_05b0e4_idx')],
                'unique_together': {('nutritionist', 'appointment_date', 'appointment_time')},
            },
        ),
    ]
