# Generated by Django 5.2.5 on 2025-10-27 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_person_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('analysis', 'Análisis Clínico'), ('recipe', 'Receta Médica'), ('image', 'Imagen'), ('report', 'Reporte'), ('other', 'Otro')], max_length=20)),
                ('title', models.CharField(help_text='Título del documento', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción adicional')),
                ('file', models.FileField(help_text='Archivo adjunto', upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.consultation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('mercadopago', 'MercadoPago'), ('card', 'Tarjeta de Crédito/Débito'), ('other', 'Otro')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('description', models.CharField(help_text='Descripción del pago', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales')),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mercadopago_preference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mercadopago_status', models.CharField(blank=True, max_length=50, null=True)),
                ('mercadopago_status_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Fecha en que se completó el pago', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.appointment')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.consultation')),
                ('nutrition_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.nutritionplan')),
                ('nutritionist', models.ForeignKey(limit_choices_to={'role': 'nutricionista'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_number', models.CharField(help_text='Número de comprobante', max_length=50, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('tax_id', models.CharField(blank=True, help_text='CUIT/CUIL', max_length=20)),
                ('fiscal_address', models.TextField(blank=True, help_text='Domicilio fiscal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='users.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['patient', 'status'], name='users_payme_patient_705da9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['nutritionist', 'status'], name='users_payme_nutriti_75599f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['mercadopago_payment_id'], name='users_payme_mercado_e55262_idx'),
        ),
    ]
