# Generated by Django 5.2.5 on 2025-10-27 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_documentattachment_payment_paymentproof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Desayuno'), ('morning_snack', 'Colación Media Mañana'), ('lunch', 'Almuerzo'), ('afternoon_snack', 'Merienda'), ('dinner', 'Cena'), ('night_snack', 'Colación Nocturna'), ('other', 'Otro')], help_text='Tipo de comida', max_length=20)),
                ('meal_date', models.DateField(help_text='Fecha de la comida')),
                ('meal_time', models.TimeField(help_text='Hora de la comida')),
                ('photo', models.ImageField(help_text='Foto de la comida', upload_to='meal_photos/')),
                ('description', models.TextField(blank=True, help_text='Descripción de la comida')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales (ej: porciones, preparación)')),
                ('estimated_calories', models.IntegerField(blank=True, help_text='Calorías estimadas', null=True)),
                ('nutritionist_comment', models.TextField(blank=True, help_text='Comentario del nutricionista')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Fecha de revisión', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_photos', to='users.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'nutricionista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meal_date', '-meal_time'],
                'indexes': [models.Index(fields=['patient', 'meal_date'], name='users_mealp_patient_d96e4f_idx'), models.Index(fields=['patient', 'created_at'], name='users_mealp_patient_8744bd_idx')],
            },
        ),
    ]
