# Generated by Django 5.2.5 on 2025-10-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS btree_gist;'),
    ]
