# Generated by Django 5.2.5 on 2025-10-24 17:04

import datetime
import django.contrib.postgres.constraints
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_enable_btree_gist'),
        ('user', '0004_useraccount_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mp', 'Mercado Pago')], default='mp', max_length=16)),
                ('currency', models.CharField(default='ARS', max_length=8)),
                ('status', models.CharField(choices=[('init', 'Init'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='init', max_length=16)),
                ('id_pago_externo', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('datos_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('ics', 'ICS (solo lectura)'), ('caldav', 'CalDAV (futuro)')], default='google', max_length=16)),
                ('external_calendar_id', models.CharField(blank=True, max_length=255)),
                ('ics_secret_token', models.CharField(blank=True, max_length=64)),
                ('privacy_generic_title', models.BooleanField(default=True)),
                ('sync_enabled', models.BooleanField(default=False)),
                ('read_busy_from_external', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nutricionista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_account', to='user.nutricionista')),
            ],
        ),
        migrations.CreateModel(
            name='PagoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('deposit', 'Depósito'), ('balance', 'Saldo'), ('fee', 'No-show fee'), ('refund', 'Reembolso')], max_length=16)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='agenda.pago')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_mode', models.CharField(choices=[('PUBLICO', 'Público'), ('INTERNO', 'Agenda interna')], default='PUBLICO', max_length=16)),
                ('payments_enabled', models.BooleanField(default=False)),
                ('payment_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mp', 'Mercado Pago'), ('cash', 'Efectivo'), ('wire', 'Transferencia'), ('card', 'Tarjeta'), ('coverage', 'Obra social')], max_length=16), default=list, size=None)),
                ('free_cancel_hours', models.PositiveIntegerField(default=24)),
                ('min_reschedule_hours', models.PositiveIntegerField(default=12)),
                ('no_show_fee_type', models.CharField(choices=[('none', 'None'), ('flat', 'Flat'), ('percent', 'Percent')], default='none', max_length=16)),
                ('no_show_fee_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('deposit_enabled', models.BooleanField(default=False)),
                ('deposit_type', models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percent')], default='flat', max_length=16)),
                ('deposit_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('anticipacion_minima', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('anticipacion_maxima', models.DurationField(default=datetime.timedelta(days=60))),
                ('buffer_before_min', models.PositiveIntegerField(default=0)),
                ('buffer_after_min', models.PositiveIntegerField(default=0)),
                ('teleconsulta_enabled', models.BooleanField(default=True)),
                ('nutricionista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='user.nutricionista')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('presencial', 'Presencial'), ('video', 'Video')], default='presencial', max_length=16)),
                ('source', models.CharField(choices=[('publico', 'Público'), ('interno', 'Interno'), ('waitlist', 'Waitlist')], default='publico', max_length=16)),
                ('tipo_consulta', models.CharField(choices=[('INICIAL', 'Inicial'), ('SEGUIMIENTO', 'Seguimiento')], max_length=32)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('slot', django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='Rango horario [start, end) para constraints')),
                ('state', models.CharField(choices=[('TENTATIVO', 'Tentativo'), ('RESERVADO', 'Reservado'), ('CONFIRMADO', 'Confirmado'), ('ATENDIDO', 'Atendido'), ('AUSENTE', 'Ausente'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=16)),
                ('payment_state', models.CharField(choices=[('NONE', 'Sin pago'), ('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('REFUNDED', 'Reembolsado'), ('FEE_CHARGED', 'No-show cobrado')], default='NONE', max_length=16)),
                ('precio_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coverage_snapshot', models.JSONField(blank=True, null=True)),
                ('intake_answers', models.JSONField(blank=True, null=True)),
                ('notas_paciente', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('soft_hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consulta_clinica', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno', to='user.consulta')),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='user.nutricionista')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='user.paciente')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='turno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='agenda.turno'),
        ),
        migrations.CreateModel(
            name='CalendarEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('ics', 'ICS (solo lectura)'), ('caldav', 'CalDAV (futuro)')], max_length=16)),
                ('external_calendar_id', models.CharField(max_length=255)),
                ('external_event_id', models.CharField(db_index=True, max_length=255)),
                ('external_etag', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_link', to='agenda.turno')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('is_virtual', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='America/Argentina/Cordoba', max_length=64)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('place_id', models.CharField(blank=True, max_length=128)),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='user.nutricionista')),
            ],
            options={
                'unique_together': {('nutricionista', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='agenda.ubicacion'),
        ),
        migrations.CreateModel(
            name='DisponibilidadHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('slot_minutes', models.PositiveIntegerField(default=30)),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='user.nutricionista')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='agenda.ubicacion')),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BloqueoDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='user.nutricionista')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='agenda.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('time_range', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=2)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='user.nutricionista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='user.paciente')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist', to='agenda.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='agenda.waitlistentry')),
                ('turno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_offer', to='agenda.turno')),
            ],
        ),
        migrations.CreateModel(
            name='MagicLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('confirm', 'Confirmar turno'), ('cancel', 'Cancelar turno'), ('reschedule', 'Reprogramar'), ('take_offer', 'Tomar oferta waitlist')], max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magic_tokens', to='user.paciente')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magic_tokens', to='agenda.turno')),
                ('waitlist_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magic_tokens', to='agenda.waitlistoffer')),
            ],
        ),
        migrations.CreateModel(
            name='ProfesionalObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('plan', models.CharField(blank=True, max_length=120)),
                ('notas', models.TextField(blank=True)),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_sociales', to='user.nutricionista')),
            ],
            options={
                'unique_together': {('nutricionista', 'nombre', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='TipoConsultaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INICIAL', 'Inicial'), ('SEGUIMIENTO', 'Seguimiento')], max_length=32)),
                ('duracion_min', models.PositiveIntegerField(default=30)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buffer_before_min', models.PositiveIntegerField(default=0)),
                ('buffer_after_min', models.PositiveIntegerField(default=0)),
                ('canal_por_defecto', models.CharField(choices=[('presencial', 'Presencial'), ('video', 'Video')], default='presencial', max_length=16)),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_consulta', to='user.nutricionista')),
            ],
            options={
                'unique_together': {('nutricionista', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=16)),
                ('template', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_meta', models.JSONField(blank=True, default=dict)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.paciente')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.nutricionista')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='agenda.turno')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'template', 'sent_at'], name='agenda_noti_channel_fc3477_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['nutricionista', 'start_time'], name='agenda_turn_nutrici_952551_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['ubicacion', 'start_time'], name='agenda_turn_ubicaci_8f0cab_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['state'], name='agenda_turn_state_a2e9df_idx'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(models.F('nutricionista'), '='), (models.F('ubicacion'), '='), (models.F('slot'), '&&')], name='no_overlap_por_prof_y_ubic'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadhoraria',
            unique_together={('nutricionista', 'ubicacion', 'dia_semana', 'hora_inicio')},
        ),
        migrations.AlterUniqueTogether(
            name='waitlistentry',
            unique_together={('nutricionista', 'paciente')},
        ),
        migrations.AddIndex(
            model_name='waitlistoffer',
            index=models.Index(fields=['expires_at'], name='agenda_wait_expires_89c309_idx'),
        ),
    ]
