# Generated by Django 5.2.5 on 2025-10-25 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='tipo_consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='agenda.tipoconsultaconfig'),
        ),
    ]
