# Generated by Django 5.2.5 on 2025-10-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_turno_tipo_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
